eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.231.4:8761/eureka/

logging:
  level:
    root: INFO
    com.logic.springjwt: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
