server:
  port: 8090 # The port your API Gateway will run on. Choose a free port.

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.231.62:8761/eureka/ # Your Eureka server IP and port
    fetch-registry: true
    register-with-eureka: true # Register the gateway with Eureka

spring:
  application:
    name: api-gateway # Name of your gateway service in Eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable discovery locator for automatic routing based on service names
          lower-case-service-id: true # Optional: Convert service IDs to lowercase
      routes:
        # Route for AIRFEILDANDRUNAWAY service
        - id: airfeildandrunaway-service
          uri: lb://AIRFEILDANDRUNAWAY # lb:// for load balancing through Eureka service ID
          predicates:
            - Path=/airfield/** # All requests to /airfield/** will be routed to AIRFEILDANDRUNAWAY
          filters:
            - StripPrefix=1 # Removes the /airfield prefix before forwarding to the service

        # Route for CGRSL service
        - id: cgrsl-service
          uri: lb://CGRSL # lb:// for load balancing through Eureka service ID
          predicates:
            - Path=/cgrsl/** # All requests to /cgrsl/** will be routed to CGRSL
          filters:
            - StripPrefix=1 # Removes the /cgrsl prefix before forwarding to the service