server:
  port: 8090 # The port your API Gateway will run on. Choose a free port.

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.231.62:8761/eureka/ # Your Eureka server IP and port
    fetch-registry: true
    register-with-eureka: true # Register the gateway with Eureka

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: gateway
    export:
      prometheus:
        enabled: true

spring:
  application:
    name: api-gateway 
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true 
          lower-case-service-id: true
      routes:
        #Reserved for MOF Common Systems
        - id: mof-common-system-management
          uri: lb://MOF_SYSTEMMANAGEMENT
          predicates:
            - Path=/systems-management/**
          filters:
            - StripPrefix=1

        - id: mof-common-user-management
          uri: lb://MOF_USERMANAGEMENT
          predicates:
            - Path=/users-management/**
          filters:
            - StripPrefix=1


        #Reserved for AEXPERT
        - id: aexpert-backend
          uri: lb://AUDITMANAGEMENTAEXPERT
          predicates:
            - Path=/audit-backend/**
          filters:
            - StripPrefix=1


        #Reserved for CGO System
        - id: nfams-user-module-exernal
          uri: lb://CGO-EXTERNALUSERMANAGEMENT
          predicates:
            - Path=/external/**
          filters:
            - StripPrefix=1

        - id: nfams-user-module-internal
          uri: lb://CGO-INTERNALUSERMANAGEMENT
          predicates:
            - Path=/internal/**
          filters:
            - StripPrefix=1

        - id: nfams-systems-management
          uri: lb://CGO-SYSTEMMANAGEMENT
          predicates:
            - Path=/management/**
          filters:
            - StripPrefix=1

        - id: nfams-vehicle-management
          uri: lb://CGO-VEHICLEMANAGEMENT
          predicates:
            - Path=/vehicle-asset/**
          filters:
            - StripPrefix=1

        - id: nfams-vehicle-report-module
          uri: lb://CGO-VEHICLEREPORTGENERATION
          predicates:
            - Path=/cgo/report/**
          filters:
            - StripPrefix=1






        #Reserved for cgo other modules(Development)
        - id: basicairfeild-cgo-service
          uri: lb://CGO-BASICAIRFIELD 
          predicates:
            - Path=/cgobasicairfield/** 
          filters:
            - StripPrefix=1

        - id: sincode-cgo-service
          uri: lb://CGO-SINCODE 
          predicates:
            - Path=/cgosincode/** 
          filters:
            - StripPrefix=1 

        - id: constructioncomplete-cgo-service
          uri: lb://CGO-CONSTRUCTIONCOMPLETE 
          predicates:
            - Path=/cgoconstructioncomplete/** 
          filters:
            - StripPrefix=1 

        - id: constructionnotcomplete-cgo-service
          uri: lb://CGO-CONSTRUCTIONNOTCOMPLETE 
          predicates:
            - Path=/cgoconstructionnotcomplete/** 
          filters:
            - StripPrefix=1 

        - id: areacalculation-cgo-service
          uri: lb://CGO-AREACALCULATION 
          predicates:
            - Path=/cgoareacalculation/** 
          filters:
            - StripPrefix=1 

        - id: dashboard-cgo-service
          uri: lb://CGO-ADMINDASHBOARD 
          predicates:
            - Path=/cgoadmindashboard/** 
          filters:
            - StripPrefix=1 