server:
  port: 8090 # The port your API Gateway will run on. Choose a free port.

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.231.62:8761/eureka/ # Your Eureka server IP and port
    fetch-registry: true
    register-with-eureka: true # Register the gateway with Eureka

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: gateway
    export:
      prometheus:
        enabled: true

spring:
  application:
    name: api-gateway 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
          lower-case-service-id: true
      routes:
        - id: basicairfeild-cgo-service
          uri: lb://CGO-BASICAIRFIELD 
          predicates:
            - Path=/cgobasicairfield/** 
          filters:
            - StripPrefix=1

        - id: sincode-cgo-service
          uri: lb://CGO-SINCODE 
          predicates:
            - Path=/cgosincode/** 
          filters:
            - StripPrefix=1 
#            -
        - id: constructioncomplete-cgo-service
          uri: lb://CGO-CONSTRUCTIONCOMPLETE 
          predicates:
            - Path=/cgoconstructioncomplete/** 
          filters:
            - StripPrefix=1 
#
        - id: constructionnotcomplete-cgo-service
          uri: lb://CGO-CONSTRUCTIONNOTCOMPLETE 
          predicates:
            - Path=/cgoconstructionnotcomplete/** 
          filters:
            - StripPrefix=1 
#
        - id: areacalculation-cgo-service
          uri: lb://CGO-AREACALCULATION 
          predicates:
            - Path=/cgoareacalculation/** 
          filters:
            - StripPrefix=1 
#
        - id: dashboard-cgo-service
          uri: lb://CGO-ADMINDASHBOARD 
          predicates:
            - Path=/cgoadmindashboard/** 
          filters:
            - StripPrefix=1 