spring:
  main:
    web-environment: true
    banner-mode: console
    debug: true

  application:
    name: TEST-SYSETEM

server:
  port: 1010
  context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: TEST-SYSETEM
    export:
      prometheus:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.231.62:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: TEST-SYSETEM:${server.port}
    prefer-ip-address: true

