spring:
  main:
    web-environment: true
    banner-mode: console
    debug: true

  application:
    name: CGRSL

server:
  port: 8088
  context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://192.168.231.62:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: cgo-structures:CGRSL:${server.port}
    prefer-ip-address: true

